apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: photo-resizer
    app.kubernetes.io/instance: picture-upload-demo
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: picture-upload
    app.kubernetes.io/managed-by: kubectl
  name: photo-resizer
spec:
  selector:
    app: photo-resizer
  ports:
  - port: 3002
